# Generated by Django 3.0.1 on 2019-12-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
