# Generated by Django 3.0.1 on 2019-12-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shuzi',
            field=models.IntegerField(default=1),
        ),
    ]
