# Generated by Django 3.0.1 on 2019-12-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0003_post_shuzi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shuzi',
        ),
    ]
