# Generated by Django 3.0.1 on 2020-01-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0004_remove_post_shuzi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
