# Generated by Django 3.0.1 on 2020-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0005_auto_20200114_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Paprika', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
