# Generated by Django 3.0.1 on 2020-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0006_auto_20200331_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip_addr',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
