# Generated by Django 3.0.1 on 2020-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0009_likes_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
