# Generated by Django 3.0.1 on 2020-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0010_auto_20200409_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ip_addr',
            field=models.CharField(max_length=50),
        ),
    ]
