# Generated by Django 3.0.1 on 2020-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0012_auto_20200411_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
