# Generated by Django 3.0.1 on 2020-04-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0014_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
