# Generated by Django 3.0.1 on 2020-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0015_auto_20200412_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ipaddr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
