# Generated by Django 3.0.1 on 2020-04-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0016_comment_ipaddr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.CharField(max_length=100),
        ),
    ]
