# Generated by Django 3.0.1 on 2020-04-15 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0019_auto_20200412_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_record',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
