# Generated by Django 3.0.1 on 2020-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0021_visitor_record_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
