# Generated by Django 3.0.1 on 2020-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipha', '0024_auto_20200801_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='private',
            field=models.BooleanField(default=0),
        ),
    ]
